[package]
name    = "ncollide_utils"
version = "0.2.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "ncollide_utils"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
rand = "*"
num = "*"
nalgebra = "*"

[dependencies.ncollide_math]
path = "../ncollide_math"
