[package]
name    = "ncollide"
version = "0.5.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "2 and 3-dimensional collision detection library in Rust."
documentation = "http://ncollide.org/doc/ncollide"
homepage = "http://ncollide.org"
repository = "https://github.com/sebcrozet/ncollide"
readme = "README.md"
keywords = [ "collision", "geometry", "distance", "ray", "convex" ]
license = "BSD-3-Clause"

include = [
    "src/**/*.rs",
    "benches/**/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[lib]
name = "ncollide"
path = "src/lib.rs"

[dependencies]
ncollide_math = "*"
ncollide_utils = "*"
ncollide_entities = "*"
ncollide_queries = "*"
ncollide_pipeline = "*"
ncollide_procedural = "*"
ncollide_transformation = "*"

[dev-dependencies]
nalgebra = "*"
rand = "*"
