[package]
name    = "ncollide"
version = "0.2.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[features]
default = [ "2df32", "2df64", "3df32", "3df64" ]
2df32 = []
2df64 = []
3df32 = []
3df64 = []

[lib]
name = "ncollide"
path = "src/lib.rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"
