[package]
name    = "ncollide_pipeline"
version = "0.2.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "ncollide_pipeline"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
nalgebra = "*"

[dependencies.ncollide_math]
path = "../ncollide_math"

[dependencies.ncollide_utils]
path = "../ncollide_utils"

[dependencies.ncollide_entities]
path = "../ncollide_entities"

[dependencies.ncollide_queries]
path = "../ncollide_queries"
