[package]
name    = "ncollide_transformation"
version = "0.2.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "ncollide_transformation"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
num = "*"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide_math]
path = "../ncollide_math"

[dependencies.ncollide_utils]
path = "../ncollide_utils"

[dependencies.ncollide_entities]
path = "../ncollide_entities"

[dependencies.ncollide_queries]
path = "../ncollide_queries"

[dependencies.ncollide_procedural]
path = "../ncollide_procedural"
