[package]
name    = "ncollide_testbed3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "ncollide_testbed3d"

[dependencies]
nalgebra = "0.8.*"
time = "0.1.*"
rand = "0.3.*"
glfw = "0.2.*"
kiss3d = "*"
mpeg_encoder = "0.2.*"

[dependencies.ncollide]
path = ".."
